### ISSUE TITLE
photonics example from our work

### ISSUE THREAD

**Issue by stevengj** [JuliaTopOpt/TopOptGridap.jl#3]
@WenjieYao has been using Gridap for photonics TopOpt, e.g. in [this paper](https://arxiv.org/abs/2111.13046), and we are putting together a relatively simple problem for https://github.com/NanoComp/photonics-opt-testbed; we are hoping to convert that to a Gridap tutorial with @fverdugo soon.

Not sure if that should go in https://github.com/gridap/Tutorials or here?

**Comment by mohdibntarek** [comment]
This is great to hear!

>Not sure if that should go in https://github.com/gridap/Tutorials or here?

I am happy with either place. If it goes here, I can try to make it more package-like and generalise it to work with the rest of the JuliaTopOpt and JuliaNonconvex ecosystems where possible. I assume the Gridap folks will want it as a tutorial though so maybe both?

**Comment by fverdugo** [comment]
Hi @stevengj @mohamed82008 !

I guess that the goal of this package (TopOptGridap.jl) is to provide helper functions to perform topop with gridap and to make it work with other parts of the JuliaTopOpt ecosystem.

In this case, I can think of two tutorials. One tutorial that uses plain calls to Gridap (in https://github.com/gridap/Tutorials), and another that uses the tools in TopOptGridap (possibly here).

**Comment by mohdibntarek** [comment]
Sounds good to me.

**Comment by mohdibntarek** [comment]
https://github.com/gridap/Tutorials/pull/142

**Comment by stevengj** [comment]
Now posted at: https://gridap.github.io/Tutorials/dev/pages/t018_TopOptEMFocus/
